import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'screens/landing_screen.dart';
import 'screens/admin_dashboard.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  const String startPage = String.fromEnvironment('page', defaultValue: 'landing');
  runApp(MyApp(startPage: startPage));
}

class MyApp extends StatelessWidget {
  final String startPage;
  const MyApp({super.key, required this.startPage});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'HRIS Biometrics',
      theme: ThemeData(
        scaffoldBackgroundColor: const Color(0xFF0A0F2E),
      ),
      home: startPage == 'admin' ? const AdminDashboard() : const LandingScreen(),
    );
  }
}